project:
  type: website
  output-dir: docs

website:
  title: "jenevievetn.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
  google-analytics:  # Begin Google Analytics block
          tracking-id: "G-JFBSZDSE1J"  # Replace "G-XXXX" with your actual Tracking ID
          anonymize-ip: true
 

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

