---
title: "About"
---

## How I made this

### Datasets

To conduct this analysis, I began by leveraging 2 key datasets. The first [data set](https://www.kaggle.com/datasets/moxxis/harry-potter-lstm?select=Harry_Potter_all_books_preprocessed.txt) contained all seven Harry Potter books in TXT format, sourced from Mateusz Kudla's repository on Kaggle.

Using R packages like `tidytext` and `textdata` packages in R, I performed additional preprocessing, segmenting the text into chapters for a more detailed analysis. The chapter-wise text was then compiled into a tibble format for streamlined data handling and analysis.

To further substantiate my analysis, I acquired a second [data set](https://www.kaggle.com/datasets/maricinnamon/harry-potter-movies-dataset) comprising dialogues from the movie series, sourced by Maryna Antonevych on Kaggle. Similar preprocessing techniques were applied, but this datset was unique in its organisation by character, enabling a deeper exploration of individual character's emotional expressions throughout the series.

### Data Visualisations

For visualisations, I utilised a combination of `ggplot2`, `plotly`, and `gganimate` packages in R, alongside developing `shiny` applications to create dynamic graphs which enhanced the overall presentation of findings.
